name: Auto Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run deployment script
        run: ./deploy.sh
